name: Deployment

on: [push]

env:
  PROJECT_ID: jdsg-coding
  GAR_LOCATION: asia-southeast1
  SERVICE: jdsg-frontend
  _ENVIRONMENT: dev

jobs:
  build:
    name: Test processed code and model

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/528130233301/locations/global/workloadIdentityPools/jdsg-pool/providers/github-provider'
        service_account: 'jdsg-wif-sa@jdsg-coding.iam.gserviceaccount.com'

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

    - name: Build and Push Container
      run: |-
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env._ENVIRONMENT }}:${{ github.sha }}" ./
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env._ENVIRONMENT }}:${{ github.sha }}"